Changes for PowerAPI monitoring

diff --git a/.github/workflows/publish-java-cdk-command.yml b/.github/workflows/publish-java-cdk-command.yml
--- a/.github/workflows/publish-java-cdk-command.yml
+++ b/.github/workflows/publish-java-cdk-command.yml
@@ -1,219 +1,147 @@
-# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
-
-# Usage: This workflow can be invoked manually or by a slash command.
-#
-# To invoke via GitHub UI, go to Actions tab, select the workflow, and click "Run workflow".
-#
-# To invoke via slash command, use the following syntax in a comment on a PR:
-#    /publish-java-cdk                # Run with the defaults (dry-run=false, force=false)
-#    /publish-java-cdk dry-run=true   # Run in dry-run mode (no-op)
-#    /publish-java-cdk force=true     # Force-publish if needing to replace an already published version
-name: Publish Java CDK
-on:
-  push:
-    branches:
-      - master
-    paths:
-      - "airbyte-cdk/java/airbyte-cdk/core/src/main/resources/version.properties"
-  workflow_dispatch:
-    inputs:
-      repo:
-        description: "Repo to check out code from. Defaults to the main airbyte repo."
-        type: choice
-        required: true
-        default: airbytehq/airbyte
-        options:
-          - airbytehq/airbyte
-      dry-run:
-        description: "Dry run (no-op)"
-        required: true
-        type: boolean
-        default: false
-      force:
-        description: "Force release (overwrite existing)"
-        required: true
-        type: boolean
-        default: false
-      gitref:
-        description: "The git ref to check out from the specified repository."
-        required: true
-      comment-id:
-        description: "Optional comment-id of the slash command. Ignore if not applicable."
-        required: false
-      pr:
-        description: "PR Number (Unused)"
-        type: number
-        required: false
-
 concurrency:
-  group: publish-java-cdk
   cancel-in-progress: false
-
+  group: publish-java-cdk
 env:
-  # Use the provided GITREF or default to the branch triggering the workflow.
+  CDK_VERSION_FILE_PATH: ./airbyte-cdk/java/airbyte-cdk/core/src/main/resources/version.properties
+  DRY_RUN: ${{ github.event_name == 'push' && 'false' || github.event.inputs.dry-run
+    == null && 'true' || github.event.inputs.dry-run }}
+  FORCE: ${{ github.event_name == 'push' || github.event.inputs.force == null && 'false'
+    ||  github.event.inputs.force }}
   GITREF: ${{ github.event.inputs.gitref || github.ref }}
-  FORCE: "${{ github.event_name == 'push' || github.event.inputs.force == null && 'false' ||  github.event.inputs.force }}"
-  DRY_RUN: "${{ github.event_name == 'push' && 'false' || github.event.inputs.dry-run == null && 'true' || github.event.inputs.dry-run }}"
-  CDK_VERSION_FILE_PATH: "./airbyte-cdk/java/airbyte-cdk/core/src/main/resources/version.properties"
   S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
   S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
-
 jobs:
   publish-cdk:
     name: Publish Java CDK
-    runs-on: connector-test-large
-    timeout-minutes: 30
+    runs-on: self-hosted
     steps:
-      - name: Link comment to Workflow Run
-        if: github.event.inputs.comment-id
-        uses: peter-evans/create-or-update-comment@v1
-        with:
-          comment-id: ${{ github.event.inputs.comment-id }}
-          body: |
-            > :clock2: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
+    - continue-on-error: true
+      if: github.event.inputs.comment-id
+      name: Link comment to Workflow Run
+      uses: peter-evans/create-or-update-comment@v1
+      with:
+        body: '> :clock2: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
 
-      - name: Checkout Airbyte
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ env.GITREF }}
+          '
+        comment-id: ${{ github.event.inputs.comment-id }}
+    - continue-on-error: true
+      name: Checkout Airbyte
+      uses: actions/checkout@v3
+      with:
+        ref: ${{ env.GITREF }}
+    - continue-on-error: true
+      id: read-target-java-cdk-version
+      name: Read Target Java CDK version
+      run: "cdk_version=$(cat $CDK_VERSION_FILE_PATH | tr -d '\\n')\necho \"CDK_VERSION=$CDK_VERSION\"\
+        \necho \"FORCE=$FORCE\"\necho \"DRY_RUN=$DRY_RUN\"\nif [[ -z \"$cdk_version\"\
+        \ ]]; then\n  echo \"Failed to retrieve CDK version from $CDK_VERSION_FILE_PATH\"\
+        \n  exit 1\nfi\necho \"CDK_VERSION=${cdk_version}\" >> $GITHUB_ENV\n"
+    - continue-on-error: true
+      name: Setup Java
+      uses: actions/setup-java@v3
+      with:
+        distribution: zulu
+        java-version: '21'
+    - continue-on-error: true
+      name: Docker login
+      uses: docker/login-action@v1
+      with:
+        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
+        username: ${{ secrets.DOCKER_HUB_USERNAME }}
+    - continue-on-error: true
+      env:
+        CI: true
+      name: Build Java CDK
+      uses: burrunan/gradle-cache-action@v1
+      with:
+        arguments: --scan :airbyte-cdk:java:airbyte-cdk:cdkBuild
+        concurrent: true
+        gradle-distribution-sha-256-sum-warning: false
+        job-id: cdk-publish
+        read-only: ${{ !(env.DRY_RUN == 'false') }}
+    - continue-on-error: true
+      env:
+        CI: true
+      if: ${{ (env.FORCE != 'true') }}
+      name: Check for Existing Version
+      uses: burrunan/gradle-cache-action@v1
+      with:
+        arguments: --scan :airbyte-cdk:java:airbyte-cdk:assertCdkVersionNotPublished
+        concurrent: true
+        gradle-distribution-sha-256-sum-warning: false
+        job-id: cdk-publish
+        read-only: true
+    - continue-on-error: true
+      env:
+        CI: true
+        CLOUDREPO_PASSWORD: ${{ secrets.CLOUDREPO_PASSWORD }}
+        CLOUDREPO_USER: ${{ secrets.CLOUDREPO_USER }}
+      if: ${{ env.DRY_RUN == 'false' }}
+      name: Publish Poms and Jars to CloudRepo
+      uses: burrunan/gradle-cache-action@v1
+      with:
+        arguments: --scan :airbyte-cdk:java:airbyte-cdk:cdkPublish
+        concurrent: true
+        execution-only-caches: true
+        gradle-distribution-sha-256-sum-warning: false
+        job-id: cdk-publish
+        read-only: true
+    - continue-on-error: true
+      if: github.event.inputs.comment-id && success()
+      name: Add Success Comment
+      uses: peter-evans/create-or-update-comment@v1
+      with:
+        body: '> :white_check_mark: Successfully published Java CDK ${{ env.CDK_VERSION
+          }}!
 
-      - name: Read Target Java CDK version
-        id: read-target-java-cdk-version
-        run: |
-          cdk_version=$(cat $CDK_VERSION_FILE_PATH | tr -d '\n')
-          echo "CDK_VERSION=$CDK_VERSION"
-          echo "FORCE=$FORCE"
-          echo "DRY_RUN=$DRY_RUN"
-          if [[ -z "$cdk_version" ]]; then
-            echo "Failed to retrieve CDK version from $CDK_VERSION_FILE_PATH"
-            exit 1
-          fi
-          echo "CDK_VERSION=${cdk_version}" >> $GITHUB_ENV
+          '
+        comment-id: ${{ github.event.inputs.comment-id }}
+        edit-mode: append
+    - continue-on-error: true
+      if: github.event.inputs.comment-id && failure()
+      name: Add Failure Comment
+      uses: peter-evans/create-or-update-comment@v1
+      with:
+        body: '> :x: Publish Java CDK ${{ env.CDK_VERSION }} failed!
 
-      - name: Setup Java
-        uses: actions/setup-java@v3
-        with:
-          distribution: "zulu"
-          java-version: "21"
-
-      - name: Docker login
-        # Some tests use testcontainers which pull images from DockerHub.
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
-
-      - name: Build Java CDK
-        uses: burrunan/gradle-cache-action@v1
-        env:
-          CI: true
-        with:
-          job-id: cdk-publish
-          read-only: ${{ !(env.DRY_RUN == 'false') }}
-          concurrent: true
-          gradle-distribution-sha-256-sum-warning: false
-          arguments: --scan :airbyte-cdk:java:airbyte-cdk:cdkBuild
-
-      - name: Check for Existing Version
-        # we only check existing version if it's a manual trigger and FORCE is set to false
-        if: ${{ (env.FORCE != 'true') }}
-        uses: burrunan/gradle-cache-action@v1
-        env:
-          CI: true
-        with:
-          job-id: cdk-publish
-          read-only: true
-          concurrent: true
-          gradle-distribution-sha-256-sum-warning: false
-          arguments: --scan :airbyte-cdk:java:airbyte-cdk:assertCdkVersionNotPublished
-
-      - name: Publish Poms and Jars to CloudRepo
-        if: ${{ env.DRY_RUN == 'false' }}
-        uses: burrunan/gradle-cache-action@v1
-        env:
-          CI: true
-          CLOUDREPO_USER: ${{ secrets.CLOUDREPO_USER }}
-          CLOUDREPO_PASSWORD: ${{ secrets.CLOUDREPO_PASSWORD }}
-        with:
-          job-id: cdk-publish
-          read-only: true
-          concurrent: true
-          execution-only-caches: true
-          gradle-distribution-sha-256-sum-warning: false
-          arguments: --scan :airbyte-cdk:java:airbyte-cdk:cdkPublish
-
-      - name: Add Success Comment
-        if: github.event.inputs.comment-id && success()
-        uses: peter-evans/create-or-update-comment@v1
-        with:
-          comment-id: ${{ github.event.inputs.comment-id }}
-          edit-mode: append
-          body: |
-            > :white_check_mark: Successfully published Java CDK ${{ env.CDK_VERSION }}!
-
-      - name: Add Failure Comment
-        if: github.event.inputs.comment-id && failure()
-        uses: peter-evans/create-or-update-comment@v1
-        with:
-          comment-id: ${{ github.event.inputs.comment-id }}
-          edit-mode: append
-          body: |
-            > :x: Publish Java CDK ${{ env.CDK_VERSION }} failed!
-
-      - name: "Post failure to Slack channel"
-        if: ${{ env.DRY_RUN == 'false' && failure() }}
-        uses: slackapi/slack-github-action@v1.23.0
-        continue-on-error: true
-        with:
-          channel-id: C04J1M66D8B
-          payload: |
-            {
-                "text": "Error during `publish-cdk` while publishing Java CDK!",
-                "blocks": [
-                    {
-                        "type": "section",
-                        "text": {
-                            "type": "mrkdwn",
-                            "text": "Error while publishing Java CDK!"
-                        }
-                    },
-                    {
-                        "type": "section",
-                        "text": {
-                            "type": "mrkdwn",
-                            "text": "See details on <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|GitHub>\n"
-                        }
-                    }
-                ]
-            }
-        env:
-          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
-
-      - name: "Post success to Slack channel"
-        if: ${{ env.DRY_RUN == 'false' && !failure() }}
-        uses: slackapi/slack-github-action@v1.23.0
-        continue-on-error: true
-        with:
-          channel-id: C04J1M66D8B
-          payload: |
-            {
-                "text": "New `${{ env.CDK_VERSION }}` version of Java CDK was successfully published!",
-                "blocks": [
-                    {
-                        "type": "section",
-                        "text": {
-                            "type": "mrkdwn",
-                            "text": "Java CDK ${{ env.CDK_VERSION }} published successfully!"
-                        }
-                    },
-                    {
-                        "type": "section",
-                        "text": {
-                            "type": "mrkdwn",
-                            "text": "See details on <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|GitHub>\n"
-                        }
-                    }
-                ]
-            }
-        env:
-          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
+          '
+        comment-id: ${{ github.event.inputs.comment-id }}
+        edit-mode: append
+    - continue-on-error: true
+      env:
+        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
+      if: ${{ env.DRY_RUN == 'false' && failure() }}
+      name: Post failure to Slack channel
+      uses: slackapi/slack-github-action@v1.23.0
+      with:
+        channel-id: C04J1M66D8B
+        payload: "{\n    \"text\": \"Error during `publish-cdk` while publishing Java\
+          \ CDK!\",\n    \"blocks\": [\n        {\n            \"type\": \"section\"\
+          ,\n            \"text\": {\n                \"type\": \"mrkdwn\",\n    \
+          \            \"text\": \"Error while publishing Java CDK!\"\n          \
+          \  }\n        },\n        {\n            \"type\": \"section\",\n      \
+          \      \"text\": {\n                \"type\": \"mrkdwn\",\n            \
+          \    \"text\": \"See details on <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|GitHub>\\\
+          n\"\n            }\n        }\n    ]\n}\n"
+    - continue-on-error: true
+      env:
+        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
+      if: ${{ env.DRY_RUN == 'false' && !failure() }}
+      name: Post success to Slack channel
+      uses: slackapi/slack-github-action@v1.23.0
+      with:
+        channel-id: C04J1M66D8B
+        payload: "{\n    \"text\": \"New `${{ env.CDK_VERSION }}` version of Java\
+          \ CDK was successfully published!\",\n    \"blocks\": [\n        {\n   \
+          \         \"type\": \"section\",\n            \"text\": {\n            \
+          \    \"type\": \"mrkdwn\",\n                \"text\": \"Java CDK ${{ env.CDK_VERSION\
+          \ }} published successfully!\"\n            }\n        },\n        {\n \
+          \           \"type\": \"section\",\n            \"text\": {\n          \
+          \      \"type\": \"mrkdwn\",\n                \"text\": \"See details on\
+          \ <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|GitHub>\\\
+          n\"\n            }\n        }\n    ]\n}\n"
+    timeout-minutes: 30
+name: Publish Java CDK
+on:
+  repository_dispatch:
+    types: trigger-ga___publish-java-cdk-command.yml
